micronaut:
  application:
    name: mercator

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/mercator`}
    username: ${DB_USER:`mercator`}
    password: ${DB_PASSWORD:`change_me`}
    driver-class-name: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true
