-- Seed the full bormeparser cargo (appointment-role) vocabulary into role.
-- The V1.0.0 baseline seeded the 16 documented canonical roles; this additive migration
-- adds the remaining 369 cargo codes ported from bormeparser's cargo.py (GPLv3, Pablo
-- Castellano; ADR-0012), so appointment.role can reference any cargo the parser
-- canonicalises onto net.earelin.mercator.domain.parse.Cargo. See
-- docs/specs/03-extraction.md §Roles.
INSERT INTO role (code, description) VALUES
    ('ADJ_GERENCIA', 'Adj. Gerencia'),
    ('ADMINISTRADOR', 'Administrador'),
    ('ADMINISTRADOR_ADJUNTO', 'Administrador adjunto'),
    ('ADMINISTRADOR_CONJUNTO', 'Administrador conjunto'),
    ('ADMINISTRADOR_MANCOMUNADO_SUPLENTE', 'Administrador mancomunado suplente'),
    ('ADMINISTRADOR_PRIMERO', 'Administrador primero'),
    ('ADMINISTRADOR_PROV', 'Administrador prov.'),
    ('ADMINISTRADOR_PROV_SOLIDARIO', 'Administrador Prov.Sol.'),
    ('ADMINISTRADOR_PROV_SOLIDARIO_EF', 'Administrador Prov.Sol.E.F.'),
    ('ADMINISTRADOR_SOLIDARIO_SUPLENTE', 'Administrador solidario suplente'),
    ('ADM_CONCURS', 'Administrador concurs.'),
    ('ADM_JUDICIAL', 'Administrador judicial'),
    ('ADM_SUPLENTE', 'Administrador suplente'),
    ('AG_REV_TIT', 'Ag.Rev.Tit.'),
    ('APODERADO_CONJUNTO', 'Apoderado conjunto'),
    ('APODERADO_D_GENERAL', 'Apoderado D. general'),
    ('APODERADO_MANCOMUNADO_SOLIDARIO', 'Apoderado mancomunado solidario'),
    ('APODERADO_SOC_UNI', 'Apoderado Soc. Uni.'),
    ('APODERADO_SOLIDARIO_MANCOMUNADO', 'Apoderado solidario mancomunado'),
    ('APODERADO_SUCURSAL', 'Apoderado sucursal'),
    ('AUDITOR_CONJUNTO', 'Auditor conjunto'),
    ('AUDITOR_CONS', 'Auditor Cons.'),
    ('AUDITOR_CUENTAS', 'Auditor de cuentas'),
    ('AUDITOR_CUENTAS_CONSOLIDADAS_CONJUNTO', 'Auditor de cuentas consolidadas conjunto'),
    ('AUDITOR_CUENTAS_CONSOLIDADAS_SUPLENTE', 'Auditor de cuentas consolidadas suplente'),
    ('AUDITOR_GRUP', 'Auditor Grup'),
    ('AUDITOR_INDIVIDUAL', 'Auditor individual'),
    ('AUDITOR_MANCOMUNADO', 'Auditor mancomunado'),
    ('AUDITOR_SUPLENTE', 'Auditor suplente'),
    ('AUDITOR_SUPLENTE_CUENTAS_CONSOLIDADAS', 'Auditor suplente cuentas consolidadas'),
    ('AUDITOR_SU_C_CON', 'Auditor suplente C.Con'),
    ('AUDITOR_TITU', 'Auditor titular'),
    ('AUDITOR_TIT_GRUP', 'Auditor Titular Grup.'),
    ('AUX_ADMINISTRADOR_CONC', 'Aux. Adm. Conc.'),
    ('CENSOR_CUENT', 'Censor Cuent'),
    ('COMISARIO', 'Comisario'),
    ('COMISARIO_SI_O', 'COMISAR.SI.O'),
    ('COMISARIO_SUP_S', 'COMISR.SUP.S'),
    ('COMISION_ACREEDORES', 'Comisión de acreedores'),
    ('COMISION_CONTROL', 'Comisión de control'),
    ('COMISION_CONTROL_Y_S', 'Comisión de control y S.'),
    ('COMISION_EJECUTIVA', 'Comisión ejecutiva'),
    ('COMISION_ESTRATEG', 'Comisión estratégica'),
    ('COMISION_LIQ', 'Comisión liq.'),
    ('COMISION_NOMB', 'Comisión de nombramientos'),
    ('COMISION_SEGUIMIENTO', 'Comisión de seguimiento'),
    ('COMI_SIN_OBLI', 'ComiSinObli'),
    ('COMS_DEL_INV', 'Comisión del inv.'),
    ('COMS_VIGILAN', 'Coms.Vigilan'),
    ('COM_AUDIT', 'Miembro del comité de aud.'),
    ('COM_AUDIT_CTRL', 'Comisión Aud.Ctrl.'),
    ('COM_CONS_FAM', 'Com. Cons. Fam.'),
    ('COM_GERENCIA', 'Com. Gerencia'),
    ('CONSEJERO_COMISION_DELEGADA', 'Consejero de la comisión delegada'),
    ('CONSEJERO_COMISION_RIESGOS', 'Consejero de la comisión de riesgos'),
    ('CONSEJERO_CONSEJO_RECTOR', 'Consejero del consejo rector'),
    ('CONSEJERO_COOR', 'Consejero Coor.'),
    ('CONSEJERO_COOR_CA', 'Consejero Coor. Ca.'),
    ('CONSEJERO_DELEGADO_JUN', 'Consejero delegado jun.'),
    ('CONSEJERO_DELEGADO_MANCOMUNADO', 'Consejero delegado mancomunado'),
    ('CONSEJERO_DELEGADO_MANCOMUNADO_SOLIDARIO', 'Consejero delegado mancomunado solidario'),
    ('CONSEJERO_DELEGADO_SUPLENTE', 'Consejero delegado suplente'),
    ('CONSEJERO_DOMINIC', 'Consejero dominic.'),
    ('CONSEJERO_EJECUTIVO', 'Consejero ejecutivo'),
    ('CONSEJERO_EXTERNO', 'Consejero externo'),
    ('CONSEJERO_EXT_DOM', 'Consejero externo Dom.'),
    ('CONSEJERO_HONORA', 'Consejero honora.'),
    ('CONSEJERO_INDEPENDIENTE', 'Consejero independiente'),
    ('CONSEJERO_IND_COOR', 'Consejero independiente Coor.'),
    ('CONSEJERO_INTERIN', 'Consejero Interin.'),
    ('CONSEJERO_OTR_EXT', 'Consejero Otr. externo'),
    ('CONSEJERO_SUPLENTE', 'Consejero suplente'),
    ('CONTADOR', 'Contador'),
    ('CONTAD_JUNTA_DIRECTIVA', 'Contador de la Junta Directiva'),
    ('COPRESIDENTE', 'Copresidente'),
    ('COPRESIDENTE_COMISION_EJECUTIVA', 'Copresidente de la comisión ejecutiva'),
    ('C_CTR_E_PROM', 'C.CTR=E.PROM'),
    ('DEF_PARTICIP', 'Def. particip'),
    ('DELEGADO', 'Delegado'),
    ('DELEGADO_GENERAL', 'Delegado general'),
    ('DEPOSITARIO', 'Depositario'),
    ('DEPOSITARIO_COMISION_CONTROL', 'Depositario de la comisión de control'),
    ('DIRECTOR', 'Director'),
    ('DIRECTOR_ADMINIS', 'Director Adminis.'),
    ('DIRECTOR_COMERCIAL', 'Director comercial'),
    ('DIRECTOR_DEPARTAMENTO', 'Director de departamento'),
    ('DIRECTOR_EJECUTIVO', 'Director ejecutivo'),
    ('DIRECTOR_EXPLOTA', 'Director Explota.'),
    ('DIRECTOR_FABRICA', 'Director fábrica'),
    ('DIRECTOR_FINANCIERO', 'Director financiero'),
    ('DIRECTOR_GENERAL', 'Director general'),
    ('DIRECTOR_GENERAL_ADJUNTO', 'Director general adjunto'),
    ('DIRECTOR_GENERAL_ADM', 'Director general Adm.'),
    ('DIRECTOR_GENERAL_FINANCIERO', 'Director general financiero'),
    ('DIRECTOR_GENERAL_SUPLENTE', 'Director general suplente'),
    ('DIRECTOR_MARKETING', 'Director de marketing'),
    ('DIRECTOR_OPERACIONES', 'Director operaciones'),
    ('DIRECTOR_RECURSOS_HUMANOS', 'Director de Recursos Humanos'),
    ('DIRECTOR_RELACIONES_LABORALES', 'Director de relaciones laborales'),
    ('DIRECTOR_SUCURSAL', 'Director de la sucursal'),
    ('DIRECTOR_TECNICO', 'Director técnico'),
    ('D_G_CONSEJO_RECTOR', 'D.G. del consejo rector'),
    ('ENTIDAD_COGESTORA', 'Entidad cogestora'),
    ('ENTIDAD_DEPOSITARIA', 'Entidad depositaria'),
    ('ENTIDAD_ENC_GESTORA', 'Entidad enc. gestora'),
    ('ENTIDAD_GESTORA', 'Entidad gestora'),
    ('ENTIDAD_GESTORA_ACT', 'Entidad gestora Act.'),
    ('ENTIDAD_GESTORA_DEL', 'Entidad gestora Del.'),
    ('ENTIDAD_GESTORA_INDEPENDIENTE', 'Entidad gestora independiente'),
    ('ENTIDAD_PROMOTORA', 'Entidad promotora'),
    ('ENT_REG_CONT', 'Entidad reg. cont.'),
    ('EXP_IND', 'Exp. ind.'),
    ('FUNDADOR', 'Fundador'),
    ('GERENTE', 'Gerente'),
    ('GERENTE_ADJUNTO', 'Gerente adjunto'),
    ('GERENTE_EJECUTIVO', 'Gerente ejecutivo'),
    ('GERENTE_SMCP', 'Gerente SMCP'),
    ('GERENTE_SUCURSAL', 'Gerente de la sucursal'),
    ('GERENTE_UNI', 'Gerente uni.'),
    ('GER_COMISION_GER', 'Gerente de la comision ger.'),
    ('GESTOR', 'Gestor'),
    ('INTERVENTOR', 'Interventor'),
    ('INTERVENTOR_JUDICIAL', 'Interventor judicial'),
    ('INTERVENTOR_SOLIDARIO', 'Interventor solidario'),
    ('INTERVENTOR_SUSPG', 'Interventor Suspg.'),
    ('LETRADO_ASESOR', 'Letrado asesor'),
    ('LIQUIDADOR_CONC', 'Liquidador conc.'),
    ('LIQUIDADOR_DEL_MANCOMUNADO', 'Liquidador del. mancomunado'),
    ('LIQUIDADOR_JUDICIAL', 'Liquidador judicial'),
    ('LIQUIDADOR_MANCOMUNADO', 'Liquidador mancomunado'),
    ('LIQUIDADOR_SUPLENTE', 'Liquidador suplente'),
    ('LIQUISOLI', 'Liquidador solidario'),
    ('MANDATARIO', 'Mandatario'),
    ('MEDIAD_CONCUSAL', 'Med.Concusal'),
    ('ME_COMITE_NOMBRAMIENTOS_Y_RETRIBUCIONES', 'Me. del comité de Nombramientos y Retribuciones'),
    ('MIEMBRO_AGPV', 'Miembro A.G.P.V.'),
    ('MIEMBRO_CDCA', 'Miembro C.D.C.A.'),
    ('MIEMBRO_COMISION', 'Miembro de la comisión'),
    ('MIEMBRO_COMISION_ACREEDORES', 'Miembro de la comisión de acreedores'),
    ('MIEMBRO_COMISION_AUDIT', 'Miembro de la comisión audit.'),
    ('MIEMBRO_COMISION_AU_CNT', 'Miembro de la comisión Au.Cnt.'),
    ('MIEMBRO_COMISION_AU_CUM', 'Miembro de la comisión Au.Cnt.'),
    ('MIEMBRO_COMISION_AYR', 'Miembro de la comisión AyR'),
    ('MIEMBRO_COMISION_CONSU', 'Miembro de la comisión Consu.'),
    ('MIEMBRO_COMISION_CONTROL', 'Miembro de la comisión de control'),
    ('MIEMBRO_COMISION_CYA', 'Miembro de la comisión CyA'),
    ('MIEMBRO_COMISION_DELEGADA', 'Miembro de la comisión delegada'),
    ('MIEMBRO_COMISION_DIRECTIVA', 'Miembro de la comisión directiva'),
    ('MIEMBRO_COMISION_EJECUTIVA', 'Miembro de la comisión ejecutiva'),
    ('MIEMBRO_COMISION_EJECUTIVA_CR', 'Miembro de la comisión ejecutiva CR.'),
    ('MIEMBRO_COMISION_ESTRATEG', 'Miembro de la comisión estratégica'),
    ('MIEMBRO_COMISION_GER', 'Miembro de la comisión Ger.'),
    ('MIEMBRO_COMISION_INDEPENDIENTE', 'Miembro de la comisión independiente'),
    ('MIEMBRO_COMISION_LIQ', 'Miembro de la comisión liq.'),
    ('MIEMBRO_COMISION_MIX', 'Miembro de la comisión mix.'),
    ('MIEMBRO_COMISION_NOM_RE', 'Miembro de la comisión Nom.Re.'),
    ('MIEMBRO_COMISION_O_S', 'Miembro de la comisión O.S.'),
    ('MIEMBRO_COMISION_REP_MUNI', 'Miembro de la comisión Rep. Muni.'),
    ('MIEMBRO_COMISION_RESPO', 'Miembro de la comisión respo.'),
    ('MIEMBRO_COMISION_RETR', 'Miembro de la comisión Retr.'),
    ('MIEMBRO_COMISION_RIESGOS', 'Miembro de la comisión de riesgos'),
    ('MIEMBRO_COMISION_SEGUIMIENTO', 'Miembro de la comisión de seguimiento'),
    ('MIEMBRO_COMISION_SEG_FO', 'Miembro de la comisión Seg. Fo.'),
    ('MIEMBRO_COMISION_SEQ', 'Miembro de la comisión Seq.'),
    ('MIEMBRO_COMISION_VIG', 'Miembro de la comisión VIG'),
    ('MIEMBRO_COMITE_CF', 'Miembro del comité CF'),
    ('MIEMBRO_COMITE_CON', 'Miembro del comité Con.'),
    ('MIEMBRO_COMITE_INV', 'Miembro del comité inv.'),
    ('MIEMBRO_COMITE_NOMBRAMIENTOS_Y_RETRIBUCIONES', 'Miembro del comité de Nombramientos y Retribuciones'),
    ('MIEMBRO_COMITE_PRO', 'Miembro del comité Pro.'),
    ('MIEMBRO_COMITE_REC', 'Miembro del comité Rec.'),
    ('MIEMBRO_COMIT_AUD', 'Miembro de la comisión Aud.'),
    ('MIEMBRO_COM_ASESO', 'Miembro del comité asesor'),
    ('MIEMBRO_COM_AUD', 'Miembro de la comisión Aud.'),
    ('MIEMBRO_COM_CTO', 'Miembro de la comisión Cto.'),
    ('MIEMBRO_COM_EIC', 'Miembro de la comisión EIC'),
    ('MIEMBRO_CONSEJERO_GO', 'Miembro consejero Go.'),
    ('MIEMBRO_CONSEJO_DIRECTIVO', 'Miembro del consejo directivo'),
    ('MIEMBRO_CONSEJO_RECTOR', 'Miembro del consejo rector'),
    ('MIEMBRO_C_COMISION_PERM', 'Miembro C. comisión perm.'),
    ('MIEMBRO_JGPV', 'Miembro J.G.P.V.'),
    ('MIEMBRO_JUNTA_DIRECTIVA', 'Miembro de la Junta Directiva'),
    ('MIEMBRO_JUNTA_RECTORA', 'Miembro de la Junta Rectora'),
    ('MIEMBRO_J_ADM', 'Miembro J. Adm.'),
    ('MIEMBRO_SUPLENTE_COMITE_REC', 'Miembro suplente del comité rec.'),
    ('MIEMBRO_S_O_CTR', 'Miembro S.O.CTR'),
    ('MI_O_C_C', 'Mi. o. c. c.'),
    ('NO_DEFINIDO', 'No definido'),
    ('OBSER_CON_AD', 'Obser. Con. Ad.'),
    ('OTORGANTE', 'Otorgante'),
    ('OTROS', 'Otros'),
    ('PRESEN_CONC', 'Presen. Conc.'),
    ('PRESIDENTE_ASAM_SO', 'Presidente Asam. So.'),
    ('PRESIDENTE_COMISION_ANR', 'Presidnete de la comisión ANR'),
    ('PRESIDENTE_COMISION_AUDIT', 'Presidente de la comisión audit.'),
    ('PRESIDENTE_COMISION_AU_CNT', 'Presidente de la comisión Au.Cnt.'),
    ('PRESIDENTE_COMISION_AU_CUM', 'Presidente de la comisión Au.Cum.'),
    ('PRESIDENTE_COMISION_AYR', 'Presidente de la comisión AyR'),
    ('PRESIDENTE_COMISION_A_YC', 'Presidente de la comisión A.YC.'),
    ('PRESIDENTE_COMISION_CONTROL', 'Presidente de la comisión de control'),
    ('PRESIDENTE_COMISION_DELEGADA', 'Presidente de la comisión delegada'),
    ('PRESIDENTE_COMISION_DIRECTIVA', 'Presidente de la comisión directiva'),
    ('PRESIDENTE_COMISION_EJECUTIVA', 'Presidente de la comisión ejecutiva'),
    ('PRESIDENTE_COMISION_GESTORA', 'Presidente de la comisión gestora'),
    ('PRESIDENTE_COMISION_INV', 'Presidente de la comisión Inv.'),
    ('PRESIDENTE_COMISION_LIQ', 'Presidente de la comisión liq.'),
    ('PRESIDENTE_COMISION_O_S', 'Presidente de la comisión O.S.'),
    ('PRESIDENTE_COMISION_RESPO', 'Presidente de la comisión respo.'),
    ('PRESIDENTE_COMISION_RIESGOS', 'Presidente de la comisión de riesgos'),
    ('PRESIDENTE_COMISION_SEGUIMIENTO', 'Presidente de la comisión de seguimiento'),
    ('PRESIDENTE_COMITE_ADM_RES', 'Presidente del comité Adm.Res.'),
    ('PRESIDENTE_COMITE_NOMBRAMIENTOS_Y_RETRIBUCIONES', 'Presidente del comité de Nombramientos y Retribuciones'),
    ('PRESIDENTE_COMITE_PRO', 'Presidente del comité Pro.'),
    ('PRESIDENTE_COMIT_AUD', 'Presidente de la comisión Aud.'),
    ('PRESIDENTE_COMS_D_I', 'Presidente de la comisión de inv.'),
    ('PRESIDENTE_COM_AUD', 'Presidente de la comisión Aud.'),
    ('PRESIDENTE_COM_EIC', 'Presidente de la comisión EIC'),
    ('PRESIDENTE_CONSEJO_DIRECTIVO', 'Presidente del consejo directivo'),
    ('PRESIDENTE_CONSEJO_RECTOR', 'Presidente del consejo rector'),
    ('PRESIDENTE_EJECUTIVO', 'Presidente ejecutivo'),
    ('PRESIDENTE_GESTOR', 'Presidente gestor'),
    ('PRESIDENTE_HONORIFICO', 'Presidente honorífico'),
    ('PRESIDENTE_JGPV', 'Presidente J.G.P.V.'),
    ('PRESIDENTE_JUNTA', 'Presidente Junta'),
    ('PRESIDENTE_JUNTA_DIRECTIVA', 'Presidente de la Junta Directiva'),
    ('PRESIDENTE_JUNTA_RECTORA', 'Presidente de la Junta Rectora'),
    ('PRESIDENTE_J_ADM', 'Presidente J.Adm.'),
    ('PRESIDENTE_SUPLENTE', 'Presidente suplente'),
    ('PROMOTOR', 'Promotor'),
    ('REPRESENTANTE', 'Representante'),
    ('REPRESENTANTE_FISCAL', 'Representante fiscal'),
    ('REPRESENTANTE_PLAN', 'Representante Plan.'),
    ('REPRESENTANTE_SUCURS', 'Representante de la sucursal'),
    ('REPRESENTANTE_SUPLENTE', 'Representante suplente'),
    ('REPR_143_RRM', 'Representante art. 143 del Reglamento del Registro Mercantil'),
    ('REPR_PERMAN', 'Representación permananente'),
    ('REP_ADM_CONC', 'Representante administrador concurs.'),
    ('RLC_PERMA', 'Representante perma.'),
    ('RLC_PER_S', 'R.L.C.Per.S.'),
    ('R_C_P_SOLMAN', 'R.C.P.SolMan'),
    ('SECRETARIO_ACTAS', 'Secretario actas'),
    ('SECRETARIO_ADJUNTO', 'Secretario adjunto'),
    ('SECRETARIO_COMISION_AUDIT', 'Secretario de la comisión audit.'),
    ('SECRETARIO_COMISION_AU_CNT', 'Secretario de la comisión Au.Cnt.'),
    ('SECRETARIO_COMISION_AYR', 'Secretario de la comisión AyR'),
    ('SECRETARIO_COMISION_CONTROL', 'Secretario de la comisión de control'),
    ('SECRETARIO_COMISION_DELEGADA', 'Secretario de la comisión delegada'),
    ('SECRETARIO_COMISION_DIRECTIVA', 'Secretario de la comisión directiva'),
    ('SECRETARIO_COMISION_EJECUTIVA', 'Secretario de la comisión ejecutiva'),
    ('SECRETARIO_COMISION_EJECUTIVA_CR', 'Secretario de la comisión ejecutiva CR.'),
    ('SECRETARIO_COMISION_EJECUTIVA_NO_CONSEJERO', 'Secretario de la comisión ejecutiva no consejero'),
    ('SECRETARIO_COMISION_INV', 'Secretario de la comisión Inv.'),
    ('SECRETARIO_COMISION_LIQ', 'Secretario de la comisión liq.'),
    ('SECRETARIO_COMISION_OP_VIN', 'Secretario de la comisión OpVin.'),
    ('SECRETARIO_COMISION_O_S', 'Secretario de la comisión O.S.'),
    ('SECRETARIO_COMITE_NOMBRAMIENTOS_Y_RETRIBUCIONES', 'Secretario del comité de Nombramientos y Retribuciones'),
    ('SECRETARIO_COMITE_PRO', 'Secretario del comité Pro.'),
    ('SECRETARIO_COMITE_REC', 'Secretario del comité Rec.'),
    ('SECRETARIO_COMIT_AUD', 'Secretario de la comisión Aud.'),
    ('SECRETARIO_CONSEJO_RECTOR', 'Secretario del consejo rector'),
    ('SECRETARIO_GCA', 'Secretario G.C.A.'),
    ('SECRETARIO_GENERAL', 'Secretario general'),
    ('SECRETARIO_GENERAL_ADJUNTO', 'Secretario general adjunto'),
    ('SECRETARIO_JGPV', 'Secretario J.G.P.V.'),
    ('SECRETARIO_JUNTA', 'Secretario Junta'),
    ('SECRETARIO_JUNTA_DIRECTIVA', 'Secretario de la Junta Directiva'),
    ('SECRETARIO_JUNTA_RECTORA', 'Secretario de la Junta Rectora'),
    ('SECRETARIO_J_ADM', 'Secretario J.Adm.'),
    ('SECRETARIO_NO_CONSEJERO', 'Secretario no consejero'),
    ('SECRETARIO_NO_CONSEJERO_COMISION_EJECUTIVA', 'Secretario no consejero de la comisión ejecutiva'),
    ('SECRETARIO_NO_CONSEJERO_GO', 'Secretario no consejero Go.'),
    ('SECRETARIO_NO_MIEN', 'Secretario no mien.'),
    ('SECRETARIO_SUPLENTE', 'Secretario suplente'),
    ('SECRETARIO_SUPLENTE_NO_CONSEJERO', 'Secretario suplente no consejero'),
    ('SEC_CM_DIR_N_CON', 'SecCmDirNCon'),
    ('SE_TEC_NO_CO', 'SE.TEC.NO CO'),
    ('SINDICO', 'Síndico'),
    ('SOCIEDADES_BENEFICIARIAS', 'Sociedades beneficiarias'),
    ('SOCIEDADES_FUSIONADAS', 'Sociedades fusionadas'),
    ('SOCIO', 'Socio'),
    ('SOCIO_COLECTIVO', 'Socio colectivo'),
    ('SOCIO_GESTOR', 'Socio gestor'),
    ('SOCIO_GEST_ACT', 'Socio gest. act.'),
    ('SOCIO_HONORIFICO', 'Socio honorífico'),
    ('SOCIO_PROFESIONAL', 'Socio profesional'),
    ('SOCIO_UNICO_PROFESIONAL', 'Socio único profesional'),
    ('SUBDIRECTOR', 'Subdirector'),
    ('SUBDIRECTOR_GENERAL', 'Subdirector general'),
    ('SUPLENTE', 'Suplente'),
    ('SUPLENTE_3_CONSEJO_RECTOR', 'Suplente 3 del consejo rector'),
    ('SUPLENTE_COMISION_ACREEDORES', 'Suplente de la comisión de acreedores'),
    ('SUPLENTE_COMISION_CONTROL', 'Suplente de la comisión de control'),
    ('SUPLENTE_COMISION_CT', 'Suplente de la comisión CT'),
    ('SUPLENTE_COMISION_LIQ', 'Suplente de la comisión liq.'),
    ('SUPLENTE_COMISION_VIG', 'Suplente de la comisión VIG'),
    ('SUPLENTE_CONSEJO_ADMINISTRACION', 'Suplente del consejo de administración'),
    ('SUPLENTE_CONSEJO_RECTOR', 'Suplente del consejo rector'),
    ('S_NO_MI_CO_E', 'S.NO.MI.CO.E'),
    ('S_N_C_C_D_I', 'Secretario no consejero de la comisión de inv.'),
    ('TESORERO', 'Tesorero'),
    ('TESORERO_COMISION_EJECUTIVA_C', 'Tesorero de la comisión ejecutiva C.'),
    ('TESORERO_CONSEJO_RECTOR', 'Tesorero del consejo rector'),
    ('TESORERO_JUNTA_DIRECTIVA', 'Tesorero de la Junta Directiva'),
    ('TESORERO_J_ADM', 'Tesorero J.Adm.'),
    ('VICEDIRECTOR', 'Vicedirector'),
    ('VICEPRESIDENTE', 'Vicepresidente'),
    ('VICEPRESIDENTE_COMISION_CONTROL', 'Vicepresidente de la comisión de control'),
    ('VICEPRESIDENTE_COMISION_DIRECTIVA', 'Vicepresidente de la comisión directiva'),
    ('VICEPRESIDENTE_COMISION_EJECUTIVA', 'Vicepresidente de la comisión ejecutiva'),
    ('VICEPRESIDENTE_COMISION_INV', 'Vicepresidente de la comisión Inv.'),
    ('VICEPRESIDENTE_COMISION_O_S', 'Vicepresidente de la comisión O.S.'),
    ('VICEPRESIDENTE_COMISION_RIESGOS', 'Vicepresidente de la comisión de riesgos'),
    ('VICEPRESIDENTE_COMITE_PRO', 'Vicepresidente del comité Pro.'),
    ('VICEPRESIDENTE_COMIT_AUD', 'Vicepresidente del comité aud.'),
    ('VICEPRESIDENTE_CONSEJO_DIRECTIVO', 'Vicepresidente del consejo directivo'),
    ('VICEPRESIDENTE_CONSEJO_RECTOR', 'Vicepresidente del consejo rector'),
    ('VICEPRESIDENTE_HONORIFICO', 'Vicepresidente honorífico'),
    ('VICEPRESIDENTE_JGPV', 'Vicepresidente J.G.P.V.'),
    ('VICEPRESIDENTE_JUNTA_DIRECTIVA', 'Vicepresidente de la Junta Directiva'),
    ('VICEPRESIDENTE_JUNTA_RECTORA', 'Vicepresidente de la Junta Rectora'),
    ('VICEPRESIDENTE_J_ADM', 'Vicepresidente J.Adm.'),
    ('VICEPRESIDENTE_PRIMERO', 'Vicepresidente primero'),
    ('VICEPRESIDENTE_PRIMERO_COM_CTO', 'Vicepresidente primero de la comisión Cto.'),
    ('VICEPRESIDENTE_SEGUNDO', 'Vicepresidente segundo'),
    ('VICEPRESIDENTE_SEGUNDO_COM_CTO', 'Vicepresidente segundo de la comisión Cto.'),
    ('VICEPRESIDENTE_SEGUNDO_JUNTA_DIRECTIVA', 'Vicepresidente segundo de la Junta Directiva'),
    ('VICEPRESIDENTE_TERCERO', 'Vicepresidente tercero'),
    ('VICESECRETARIO', 'Vicesecretario'),
    ('VICESECRETARIO_COMISION_CONTROL', 'Vicesecretario de la comisión de control'),
    ('VICESECRETARIO_COMISION_DELEGADA', 'Vicesecretario de la comisión delegada'),
    ('VICESECRETARIO_COMISION_EJECUTIVA', 'Vicesecretario de la comisión ejecutiva'),
    ('VICESECRETARIO_COMISION_INV', 'Vicesecretario de la comisión Inv.'),
    ('VICESECRETARIO_COMISION_O_S', 'Vicesecretario de la comisión O.S.'),
    ('VICESECRETARIO_COMITE_REC', 'Vicesecretario del comité Rec.'),
    ('VICESECRETARIO_CONSEJO_RECTOR', 'Vicesecretario del consejo rector'),
    ('VICESECRETARIO_C_E', 'Vicesecretario C.E'),
    ('VICESECRETARIO_JUNTA_DIRECTIVA', 'Vicesecretario de la Junta Directiva'),
    ('VICESECRETARIO_NO_CONSEJERO', 'Vicesecretario no consejero'),
    ('VICESECRETARIO_NO_CONSEJERO_SEGUNDO', 'Vicesecretario no consejero segundo'),
    ('VICESECRETARIO_PRIMERO', 'Vicesecretario primero'),
    ('VICESECRETARIO_PRIMERO_COM_CTO', 'Vicepresecretario primero de la comisión Cto.'),
    ('VICESECRETARIO_PRIMERO_NO_CONSEJERO', 'Vicesecretario primero no consejero'),
    ('VICESECRETARIO_SEGUNDO_COM_CTO', 'Vicepresecretario segundo de la comisión Cto.'),
    ('VICESECRETARIO_SEGUNDO_JUNTA_DIRECTIVA', 'Vicesecretario segundo de la Junta Directiva'),
    ('VICESECRETARIO_SEGUNDO_NO_CONSEJERO', 'Vicesecretario segundo no consejero'),
    ('VICESECRETARIO_TERCERO_NO_CONSEJERO', 'Vicesecretario tercero no consejero'),
    ('VICETESORERO', 'Vicetesorero'),
    ('VICETESORERO_JUNTA_DIRECTIVA', 'Vicetesorero de la Junta Directiva'),
    ('VOCAL', 'Vocal'),
    ('VOCAL_1', 'Vocal 1'),
    ('VOCAL_10_CONSEJO_RECTOR', 'Vocal 10 del consejo rector'),
    ('VOCAL_10_JUNTA_DIRECTIVA', 'Vocal 10 de la Junta Directiva'),
    ('VOCAL_2', 'Vocal 2'),
    ('VOCAL_2_JUNTA_DIRECTIVA', 'Vocal 2 de la Junta Directiva'),
    ('VOCAL_3_CONSEJO_RECTOR', 'Vocal 3 del consejo rector'),
    ('VOCAL_3_JUNTA_DIRECTIVA', 'Vocal 3 de la Junta Directiva'),
    ('VOCAL_4_CONSEJO_RECTOR', 'Vocal 4 del consejo rector'),
    ('VOCAL_4_JUNTA_DIRECTIVA', 'Vocal 4 de la Junta Directiva'),
    ('VOCAL_6_CONSEJO_RECTOR', 'Vocal 6 del consejo rector'),
    ('VOCAL_6_JUNTA_DIRECTIVA', 'Vocal 6 de la Junta Directiva'),
    ('VOCAL_7_JUNTA_DIRECTIVA', 'Vocal 7 de la Junta Directiva'),
    ('VOCAL_8_CONSEJO_RECTOR', 'Vocal 8 del consejo rector'),
    ('VOCAL_COMIT_AUD', 'Vocal Comit. Aud.'),
    ('VOCAL_E_P_JUNTA_DIRECTIVA', 'Vocal E.P. Junta Directiva'),
    ('VOCAL_JUNTA_DIRECTIVA', 'Vocal de la Junta Directiva'),
    ('VOCAL_JUNTA_RECTORA', 'Vocal de la Junta Rectora'),
    ('VOCAL_SECUNDARIO_JUNTA_DIRECTIVA', 'Vocal secundario de la Junta Directiva'),
    ('VOCAL_SUPLENTE', 'Vocal suplente'),
    ('VS_N_C_C_D_I', 'Vicesecretario no consejero de la comisión de inv.');
